"""Self-enhancement bias detector.

Measures whether the judge model gives higher scores to its own outputs
compared to outputs from other models.
"""

from judgebench.models import JudgeVerdict, LabeledPair


def detect(
    pairs: list[LabeledPair],
    verdicts: list[JudgeVerdict],
    judge_model: str,
) -> float:
    """Compute self-enhancement delta.

    Compares the win rate of responses generated by the judge model vs
    responses generated by other models. The delta is:
        (self_win_rate - other_win_rate)

    Pairs are identified as "self-generated" when metadata contains
    {"source_model": "<judge_model>"} on either response_a or response_b side.

    Specifically, metadata keys "source_model_a" and "source_model_b" indicate
    which model generated each response.

    Args:
        pairs: List of labeled pairs with metadata
        verdicts: List of judge verdicts
        judge_model: The model ID used as judge

    Returns:
        Delta between self win rate and other win rate.
        Positive = judge favors its own outputs.
        Returns 0.0 if no self-generated responses found.
    """
    pair_map = {p.id: p for p in pairs}
    verdict_map = {v.pair_id: v for v in verdicts}

    self_wins = 0
    self_total = 0
    other_wins = 0
    other_total = 0

    for pair in pairs:
        verdict = verdict_map.get(pair.id)
        if verdict is None:
            continue

        source_a = pair.metadata.get("source_model_a", "")
        source_b = pair.metadata.get("source_model_b", "")
        choice = verdict.forward_choice

        a_is_self = source_a == judge_model
        b_is_self = source_b == judge_model

        if not a_is_self and not b_is_self:
            # Neither response is from the judge model — skip for self-enhancement
            continue

        if a_is_self:
            self_total += 1
            if choice == "a":
                self_wins += 1

        if b_is_self:
            self_total += 1
            if choice == "b":
                self_wins += 1

        if not a_is_self:
            other_total += 1
            if choice == "a":
                other_wins += 1

        if not b_is_self:
            other_total += 1
            if choice == "b":
                other_wins += 1

    if self_total == 0:
        return 0.0

    self_rate = self_wins / self_total
    other_rate = other_wins / other_total if other_total > 0 else 0.5

    return self_rate - other_rate
